"""AutoTrades auction-state signal-engine package.

This package exposes strict contracts plus a causal Common Evidence Ledger, a
chronological Auction State Engine, unified boundary episodes, setup candidates,
a stock-day opportunity ledger, deterministic local opportunity arbitration and
a signal-agnostic local decision. It does not read signal/trade state, create persistence payloads or write engine state.
"""

from services.auction_engine.contracts import (
    AuctionEngineResult,
    AuctionState,
    AuctionStateName,
    BarEvidence,
    BoundaryEpisode,
    BoundaryEpisodeStatus,
    BoundaryObservation,
    BoundaryResolution,
    BoundarySide,
    CandidateEligibility,
    CandidateRole,
    CompressionEvidence,
    ConfidenceChannel,
    ContextAlignment,
    ContractModel,
    DerivativesContextEvidence,
    DirectionalBias,
    EvidenceFact,
    EvidencePolarity,
    EvidenceSnapshot,
    ExtensionEvidence,
    LocalDecision,
    LocalDecisionAction,
    FrozenRange,
    ManagerAction,
    ManagerDecision,
    MarketContextEvidence,
    OpportunityEvidence,
    OutcomeMetrics,
    PriceActionEvidence,
    QualityStatus,
    Reason,
    RunManifest,
    SetupCandidate,
    SetupFamily,
    SourceQuality,
    StoredStateEnvelope,
    TradeSide,
    TrendEvidence,
    stable_key,
)
from services.auction_engine.boundary_engine import (
    BoundaryChronologyError,
    BoundaryEpisodeEngine,
    BoundaryEvaluation,
)
from services.auction_engine.engine import AuctionEngine
from services.auction_engine.setup_engine import SetupCandidateEngine
from services.auction_engine.opportunity_ledger import OpportunityLedger
from services.auction_engine.setup_manager import SetupManager
from services.auction_engine.decision_engine import DecisionEngine
from services.auction_engine.evidence import EvidenceBuildError, EvidenceBuilder
from services.auction_engine.state_engine import (
    AuctionStateChronologyError,
    AuctionStateEngine,
    StateEvaluation,
)

__all__ = [
    "TradeSide",
    "BoundarySide",
    "DirectionalBias",
    "QualityStatus",
    "EvidencePolarity",
    "AuctionStateName",
    "BoundaryEpisodeStatus",
    "BoundaryResolution",
    "SetupFamily",
    "CandidateEligibility",
    "CandidateRole",
    "ContextAlignment",
    "ManagerAction",
    "LocalDecisionAction",
    "ContractModel",
    "Reason",
    "SourceQuality",
    "EvidenceFact",
    "ConfidenceChannel",
    "BarEvidence",
    "PriceActionEvidence",
    "BoundaryObservation",
    "TrendEvidence",
    "CompressionEvidence",
    "ExtensionEvidence",
    "OpportunityEvidence",
    "MarketContextEvidence",
    "DerivativesContextEvidence",
    "EvidenceSnapshot",
    "AuctionState",
    "FrozenRange",
    "BoundaryEpisode",
    "SetupCandidate",
    "ManagerDecision",
    "LocalDecision",
    "StoredStateEnvelope",
    "AuctionEngineResult",
    "RunManifest",
    "OutcomeMetrics",
    "stable_key",
    "EvidenceBuildError",
    "EvidenceBuilder",
    "BoundaryChronologyError",
    "BoundaryEpisodeEngine",
    "BoundaryEvaluation",
    "AuctionStateChronologyError",
    "AuctionStateEngine",
    "StateEvaluation",
    "AuctionEngine",
    "SetupCandidateEngine",
    "OpportunityLedger",
    "SetupManager",
    "DecisionEngine",
]
